DROP DATABASE IF EXISTS sell;

CREATE DATABASE sell;

\c sell;

CREATE TABLE company (
  ID INT PRIMARY KEY,
  SYMBOL CHAR(10),
  COMPANYNAME TEXT,
  MARKETPRICE NUMERIC(10, 2));


  \copy company(ID, SYMBOL, COMPANYNAME, MARKETPRICE)FROM '/out.csv' DELIMITER ',' CSV HEADER;
